### ISSUE TITLE
Execution of docs repo failing  --- requires pandas_sphinx_theme

### ISSUE THREAD

**Issue by jstac** [ExecutableBookProject/cli#20]
```
pip install -e .
```

followed by 

```
jupyter-book build 
```

fails due to lack of pandas_sphinx_theme.

```
jupyter-book build 
Traceback (most recent call last):
  File "/home/john/anaconda3/bin/jupyter-book", line 11, in <module>
    load_entry_point('jupyter-book', 'console_scripts', 'jupyter-book')()
  File "/home/john/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/john/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/home/john/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/home/john/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/john/sync_dir/quantecon/ExecutableBookProject/cli/jupyter_book/__init__.py", line 4, in <module>
    from pandas_sphinx_theme import setup as pandas_setup
ModuleNotFoundError: No module named 'pandas_sphinx_theme'
```

**Comment by choldgraf** [comment]
ah nice catch - I think this is because there weren't quite the right setup requirements, should be fixed now
