### ISSUE TITLE
Create fails while copying images

### ISSUE THREAD

**Issue by jonasdaugalas** [ExecutableBookProject/cli#61]
Using `pip install git+https://github.com/ExecutableBookProject/cli.git@master`.

```
> jupyter-book create jbook
Traceback (most recent call last):
  File "/home/jonas/anaconda3/envs/py37/bin/jupyter-book", line 8, in <module>
    sys.exit(main())
  File "/home/jonas/anaconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jonas/anaconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jonas/anaconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jonas/anaconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jonas/anaconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jonas/anaconda3/envs/py37/lib/python3.7/site-packages/jupyter_book/commands/__init__.py", line 129, in create
    sh.copy2(PATH_IMAGE, PATH_OUTPUT_IMAGES)
  File "/home/jonas/anaconda3/envs/py37/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/jonas/anaconda3/envs/py37/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jonas/anaconda3/envs/py37/lib/python3.7/site-packages/docs/images/logo.png'
```

**Comment by choldgraf** [comment]
Arg good catch - I think that's because the logo isn't making it through the `package data` properly. I'll just add the logo in the `book_template`, PR incoming

**Comment by choldgraf** [comment]
OK I think this should be fixed now, try updating master and seeing if it works! (#62 )

**Comment by jonasdaugalas** [comment]
Now `create` works. Cool!
